### ISSUE TITLE
About validation during training

### ISSUE THREAD

**Issue by ly3ym** [cagrikymk/JAX-ReaxFF#15]
Hello developer, when I was training the system, I found that there seems to be no validation in the training process, how can I make sure that my parameter optimization process is not overfitted?

**Comment by cagrikymk** [comment]
Hello,
I am working on a new version of the code and I will include the validation data support there. I will be done with the development in a week or so and update the code in the master branch with the new version.

https://github.com/cagrikymk/JAX-ReaxFF/tree/jax-reaxff-v0.2

**Comment by cagrikymk** [comment]
I updated the code in the master branch and put an example of it in the README file.
