### ISSUE TITLE
How to set to double precision？

### ISSUE THREAD

**Issue by xxlliu** [cagrikymk/JAX-ReaxFF#16]
Dear author,
Hello! You mentioned in the article that the optimization of the disulfide force field because of the training focused on the presence of the force project, in order to obtain better optimization results, you need to change to double precision. Does the double precision here mean changing the float data type in the code to 64 bits? And the specific operation steps of changing to double precision.
Thank you for your time！

**Comment by cagrikymk** [comment]
Hello,
I have a new version of the code which comes with automated tests and double precision by default as the code is fast enough for most cases and single precision accuracy gets tricky for certain functional forms, especially when training against force data.

The code is located here: https://github.com/cagrikymk/JAX-ReaxFF/tree/jax-reaxff-v0.2

Once I finish developing the code, I will replace the master brach with this one.

**Comment by cagrikymk** [comment]
The code in the master branch now supports double precision by default.
