### ISSUE TITLE
CUDA_ERROR_MISALIGNED_ADDRESS while running JAX-ReaxFF

### ISSUE THREAD

**Issue by houdingyu** [cagrikymk/JAX-ReaxFF#23]
Hi, recently I am using JAX-ReaxFF to optimize some Si-N parameters for my system. However, I ran into the error "CUDA_ERROR_MISALIGNED_ADDRESS" and I did not understand why. If delete some items in the trainset.in file, then the program can run normally. However, those items are necessary for my system, and I cannot detect any problem in those items. I have attached my input files. Could you please have a look at why JAX-ReaxFF can not run with the trainset_err.in file? 
Thank you very much!
[Si_N_opt.zip](https://github.com/user-attachments/files/15755929/Si_N_opt.zip)

**Comment by houdingyu** [comment]
In addition, I found that the CPU version can run normally.

**Comment by cagrikymk** [comment]
Hello, sorry for the delayed fix. This issue stems from XLA (the compiler used in JAX). Upgrading JAX to >=0.4.26 fixes the issue. I will push an update soon.
